### ISSUE TITLE
helm 部署时 arkid-etcd 会报 permission denied

### ISSUE THREAD

**Issue by chenchensheng** [longguikeji/arkid#1510]
用默认提供的 https://gitee.com/longguikeji/arkid-charts/raw/main/arkid.yaml 部署时 arkid-etcd 组件会报 permission denied
需加入以下配置
```yaml
    apisix:
      etcd:
        volumePermissions: 
          enabled: true
```
